        set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}"

bind ";" command-prompt -p "Pane title:" "select-pane -T '%%'"

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g automatic-rename off

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g escape-time 0
set -g extended-keys on

run '~/.tmux/plugins/tpm/tpm'
