eval "$(/opt/homebrew/bin/brew shellenv)"

export EDITOR="emacs -nw"

# COMMAND LINE HISTORY
export HISTSIZE=
export HISTFILESIZE=
export HISTFILE=~/.bash_eternal_history
# Disable Bash Sessions on Mac
SHELL_SESSION_HISTORY=0
# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups  
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
# After each command, append to the history file and reread it
export PROMPT_COMMAND="history -a"
# export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
# export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
# export PROMPT_COMMAND=

# CLAUDE

alias claude-mxns="CLAUDE_CONFIG_DIR=~/.claude-mxns claude"
alias claude-ffid="CLAUDE_CONFIG_DIR=~/.claude-ffid claude"

# CONVENIENCE

b64() {
    local use_jq=false
    local use_xq=false
    local OPTIND
    while getopts "x" opt; do
        case "$opt" in
            j) use_jq=true ;;
            x) use_xq=true ;;
        esac
    done
    shift $((OPTIND-1))

    if [ "$use_jq" = true ]; then
        echo "$1" | base64 -d | jq
    elif [ "$use_xq" = true ]; then
        echo "$1" | base64 -d | xq
    else
        echo "$1" | base64 -d
    fi
}

pick() {
    while read i; do
	printf %s "$i? (y/n) " >/dev/tty
	read response </dev/tty
	case $response in
    	    y) echo $i;;
	    q) break;;
	esac
    done
}

dzap() {
    docker ps -a | sed '1d' | docker ps -a --format "{{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}" | pick | cut -c1-12 | xargs -I % bash -c 'docker kill %; docker rm %'
}

mariadb() {
    while getopts "t" arg; do
        case ${arg} in
            t)
                TAIL_LOGS=True
                ;;
            :)
                echo "$0: Must supply an argument to -$OPTARG."
                exit 1
                ;;
            ?)
            echo "Invalid option: $OPTIND"
            exit 1
            ;;
        esac
    done
    docker run --name mariadb --env MARIADB_ROOT_PASSWORD='yourStrong(!)Password' \
           -p 3306:3306 --name mariadb -d \
           fortifiedid.jfrog.io/default-docker-local/fortifiedid/mariadb:lts
    if [ -n "$TAIL_LOGS" ]; then
        docker logs -f mariadb
    fi
}

mssql() {
    while getopts "t" arg; do
        case ${arg} in
            t)
                TAIL_LOGS=True
                ;;
            :)
                echo "$0: Must supply an argument to -$OPTARG."
                exit 1
                ;;
            ?)
            echo "Invalid option: $OPTIND"
            exit 1
            ;;
        esac
    done
    docker run -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=yourStrong(!)Password' \
           -p 1433:1433 --name db -d \
           fortifiedid.jfrog.io/default-docker-virtual/fortifiedid/mssql/server:2022-latest
    if [ -n "$TAIL_LOGS" ]; then
        docker logs -f db
    fi
}

openldap() {
    while getopts "t" arg; do
        case ${arg} in
            t)
                TAIL_LOGS=True
                ;;
            :)
                echo "$0: Must supply an argument to -$OPTARG."
                exit 1
                ;;
            ?)
            echo "Invalid option: $OPTIND"
            exit 1
            ;;
        esac
    done
    docker run -e 'LDAP_TLS=false' \
           -p 389:389 --name openldap -d \
           test-scenarios/forms/search/openldap:latest
    if [ -n "$TAIL_LOGS" ]; then
        docker logs -f openldap
    fi
}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/mxns/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/mxns/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/mxns/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/mxns/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/mxns/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/Users/mxns/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mxns/google-cloud-sdk/path.bash.inc' ]; then . '/Users/mxns/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mxns/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/mxns/google-cloud-sdk/completion.bash.inc'; fi

# Added by Windsurf
# export PATH="/Users/mxns/.codeium/windsurf/bin:$PATH"

export PATH="$HOME/.local/bin:$PATH"
